[versions]
asm = "9.3"
configurate = "4.1.2"
junit = "5.9.1"
kotlin = "1.7.10"
log4j = "2.18.0"

[libraries]
annotations = "org.jetbrains:annotations:23.0.0"
apiguardian = "org.apiguardian:apiguardian-api:1.1.2"
asm-core = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm-util = { module = "org.ow2.asm:asm-util", version.ref = "asm" }
clikt = "com.github.ajalt.clikt:clikt:3.5.0"
configurate-core = { module = "org.spongepowered:configurate-extra-kotlin", version.ref = "configurate" }
configurate-hocon = { module = "org.spongepowered:configurate-hocon", version.ref = "configurate" }
coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4"
csv = "org.apache.commons:commons-csv:1.9.0"
guice = "com.google.inject:guice:5.1.0"
jansi = "org.fusesource.jansi:jansi:2.4.0"
junit-core = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-launcher = "org.junit.platform:junit-platform-launcher:1.9.1"
juniversalchardet = "com.github.albfernandez:juniversalchardet:2.4.0"
logging-api = "org.slf4j:slf4j-api:1.7.36"
logging-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
logging-impl = { module = "org.apache.logging.log4j:log4j-slf4j-impl", version.ref = "log4j" }
serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.0"

[bundles]
junit = ["junit-core", "junit-engine", "junit-launcher"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.github.johnrengelman.shadow", version = "7.1.2" }
style = { id = "org.sourcegrade.style", version = "2.1.0" }
